<?php

/**
 * @file
 * Contains dolebas_uploader.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function dolebas_uploader_theme() {
  return [
    'wistia_views_field' => [
      'template' => 'wistia_views_field',
      'render element' => 'children',
    ],
     'cloudinary_views_field' => [
       'template' => 'cloudinary_views_field',
       'render element' => 'children',
     ],
  ];
}
