<?php

/**
 * @file
 * Contains dolebas_uploader.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function dolebas_uploader_theme() {
  return [
    'wistia_views_field' => array(
        'template' => 'wistia_views_field',
        'render element' => 'children',
        'variables' => array(
            'div_uuid' => NULL
        )        
    ),
    'cloudinary_views_field' => array(
        'template' => 'cloudinary_views_field',
        'render element' => 'children',
        'variables' => array(
            'div_uuid' => NULL
        )  
    ),
  ];
}
