<?php

/**
 * @file
 * Contains wistia_video_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wistia_video_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wistia_video_field module.
    case 'help.page.wistia_video_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Wistia Video Field') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function wistia_video_field_theme() {
  return [
    'wistia_video_field' => [
      'template' => 'wistia_video_field',
      'render element' => 'children',
    ],
  ];
}
